name: Makefile CI

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          mkdir -p ~/.ssh
          cat >> ~/.ssh/known_hosts <<< "${{ secrets.HOST_KEY }}"
          cat >> ~/.ssh/config <<< "${{ secrets.SSH_CONFIG }}"
          
    - name: deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: make deploy
